### PR TITLE
Error refactoring

### PR DESCRIPTION
**Pull request by steinymity**
I did some refactoring of the error handling mechanisms and tried to address the issues #71 and #72.
I introduced a new `ApiError` for custom errors with message and optional code and data. The usage of `KeyError` for method-not-found and `TypeError` for invalid params have been replaced by custom exceptions, so that there is no confusion between these client errors and other internal server errors.

A point for discussion is whether to keep `AssertionErrors` causing an `InvalidParamsResponse`. While assertions can be used for argument validation they might also simply check internal server invariants which should cause a generic server error.

Note: I only tested against py37. Can sb run the tests on 3.6 and 3.8, please?

### CODE REVIEW

**Comment by bcb** [comment]
Do you mind splitting this into two PRs, one for #71 and one for #72?

The one for #72 should target the 5.0 branch since it’s a breaking change. #71 can go to master.

**Comment by steinymity** [comment]
Sure, no worries. So, I guess the `InvalidArgumentsError` should target the 5.0 branch, too?

**Comment by bcb** [comment]
It’s not breaking so it can go into a minor release, as long as we leave AssertionError for now.

**Comment by steinymity** [comment]
Ok, sure, I don't mind getting this into a minor. I have opened #94 and #95, so we can merge these things separately (or together).

**Pull request closed without merging**
