### PR TITLE
Avoid interpreting `KeyError` and `TypeError` as method-not-found and invalid params

### PR DESCRIPTION
**Pull request by steinymity**
This addresses #72 and is targeted for the 5.0 branch.
The first two commits are already included in PR #94 .
A point for discussion is whether to keep AssertionErrors causing an InvalidParamsResponse. While assertions can be used for argument validation they might also simply check internal server invariants which should cause a generic server error.

### CODE REVIEW

**Comment by bcb** [comment]
Could we add the new exceptions without removing the existing ones? This way it’s not a breaking change. The removal of the existing ones can go into 5.0.

**Comment by steinymity** [comment]
I just uploaded a new version with the legacy exceptions and rebased it onto #94. So, this can then directly go into 4.0?

**Comment by bcb** [comment]
Yep looks good, won’t break for existing users. It’s doing three different things, generally I’d prefer separate PRs, as it stands it’ll need extensive testing before accepting.

**Comment by steinymity** [comment]
You could consider #94 first, which already includes the first three commits of this PR.

**Comment by bcb** [comment]
Still some outstanding comments on #94 @steinymity

**Comment by steinymity** [comment]
Shouldn't that be suitable for the 4.x branch since I re-added the legacy `except` blocks (`TypeError`, `KeyError`) in `dispatcher.py`?
IMHO, for 5.0 we should really consider removing these exceptions to avoid misinterpreting random failures in methods.

**Comment by bcb** [comment]
Thanks for reminding me, I’ll merge into master

**Comment by bcb** [comment]
Merged into master.

**Comment by bcb** [comment]
@steinymity  I’m writing the changelog for the new release, and I’m not clear on why we’ve replaced TypeError with InvalidArgumentsError when checking the params against the function signature. TypeError is fine in this case.

InvalidArgumentsError should be to replace assert when validating user input. It should be explicitly raised inside methods. (In fact it should be InvalidParamsError to match the spec.)

But for checking the arguments against the signature, TypeError is sufficient in my opinion.

**Comment by bcb** [comment]
This is where I'm confused about where ApiError fits - the example you've given in the docs (invalid path) could really be raised as an InvalidParamsError.

**Comment by bcb** [comment]
Suggest we either scrap InvalidParamsError or ApiError, essentially they're the same.

**Comment by steinymity** [comment]
> But for checking the arguments against the signature, TypeError is sufficient in my opinion.
The disadvantage of just using TypeError is that it might just indicate a random programming error in a method — it is not necessarily a client-side error. So, responding with invalid params is not always reasonable.
The same actually applies to AssertionError — it might simply point to a server side error which has nothing to do with the client doing something wrong.

**Comment by steinymity** [comment]
> This is where I'm confused about where ApiError fits - the example you've given in the docs (invalid path) could really be raised as an InvalidParamsError.

Maybe the example does not fit perfectly. My reasoning was that reading a file might fail for a ton of reasons (see e.g. manpage [read(2)](https://man.cx/read(2))) and the author of such a method might want to expose these details to the client. By using `ApiError` he can actually include `errno` and other data in the response. If reading a file failed it might point to a client error but there is no necessity that it actually does.

**Comment by steinymity** [comment]
> Let’s keep both since they’re different parts of the spec, but I’ll make a small adjustment to the invalid params exception.

Sure — I agree that `InvalidParamsError` is a better name and that catching `AssertionError`s has several disadvantages.

**Comment by bcb** [comment]
> The disadvantage of just using TypeError is that it might just indicate a random programming error in a method

This is true for AssertionError and KeyError, but TypeError is only being caught when we’re checking if the supplied values match the signature of the method. Not when the method is executed.

**Comment by bcb** [comment]
We still need InvalidParamsError for validating inside the method (replacing AssertionError).

**Comment by steinymity** [comment]
> TypeError is only being caught when we’re checking

Are you sure about that?

I just added this test case using the current master branch (d1deccd), and it fails:
``` python
def test_safe_call_method_failure():
    def fail():
        raise TypeError()

    response = safe_call(Request(method="fail", id=1), Methods(fail), debug=True)
    assert isinstance(response, ExceptionResponse)
```
According to the error message, `safe_call` indeed returns an `InvalidParamsResponse`:
```
E       assert False
E        +  where False = isinstance(<jsonrpcserver.response.InvalidParamsResponse object at 0x7f36f6533550>, ExceptionResponse)
```
When I only change `raise TypeError()` into `raise ValueError()`, the test passes.

Since `handle_exceptions()` is a context manager, exceptions thrown in the body of the with-clause, including inside the methods, are caught in `handle_exceptions()`'s try-except statement.

**Comment by bcb** [comment]
You're right, I thought it was being handled separately.

@steinymity I'm preparing the release PR, would you mind reviewing it when it's ready?

**Comment by steinymity** [comment]
@bcb  No, I don't mind. I'm happy if I can help :) Just add me to the PR.

**Comment by bcb** [comment]
Great. Added you as reviewer to #100.

**Pull request merged**
