### PR TITLE
Prepare version 4.1.0

### PR DESCRIPTION
**Pull request by bcb**

### CODE REVIEW

**Comment by bcb** [comment]
This PR is all that’s left for the release, @steinymity. Mostly documentation, but I think it needs work. Will try to look at it ASAP.

**Comment by steinymity** [comment]
Ok, sounds great! Maybe we should mention `ApiError` in the changelog, too, so ppl. know it's available?

**Comment by bcb** [comment]
Yes it should be there.

**Comment by bcb** [comment]
@steinymity There are three outstanding pull requests. Once you've approved I'll go ahead and release.

**Pull request merged**
